---
version: '3'

services:
  database:
    image: mysql:5.6
    container_name: uka-database
    ports:
      - 127.0.0.1:3306:3306
    env_file:
      # contains
      # - MYSQL_ROOT_PASSWORD
      - database-secrets.env
    volumes:
      - /home/core/data/uka-database-var-lib-mysql/:/var/lib/mysql/
    restart: always
    networks:
      - uka

  webserver:
    image: blindernuka/webserver
    build:
      context: webserver
      dockerfile: Dockerfile
    ports:
      - 8085:80
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    environment:
      # TODO: We should use a README or something, but currently none exists
      CONTAINER_USERFILE: /project/uka/web/.gitignore
    volumes:
      - /home/core/web:/project/uka/web
    restart: always
    networks:
      - uka

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=uka-database
    ports:
      - 127.0.0.1:8083:80
    networks:
      - uka
    volumes:
      - /sessions

networks:
  uka:
    external: true
